-- 코드를 작성해주세요

SELECT CONCAT(SUB.QUARTER, 'Q') AS QUARTER , COUNT(*) AS ECOLI_COUNT FROM (
    SELECT ID, QUARTER(DIFFERENTIATION_DATE) AS QUARTER FROM ECOLI_DATA
) AS SUB
GROUP BY SUB.QUARTER
ORDER BY SUB.QUARTER;