-- 코드를 입력하세요
SELECT CONCAT("/home/grep/src/", ugf.BOARD_ID, "/", ugf.FILE_ID, ugf.FILE_NAME, ugf.FILE_EXT) as FILE_PATH FROM USED_GOODS_FILE as ugf 
LEFT JOIN USED_GOODS_BOARD as ugb ON ugf.BOARD_ID = ugb.BOARD_ID
WHERE ugb.VIEWS IN (SELECT MAX(sub.VIEWS) FROM USED_GOODS_BOARD as sub)
ORDER BY ugf.FILE_ID DESC;